// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxvXWII9AAgEcqAOawh7Eoe9Oi7ANUe5Y',
    appId: '1:623449718136:web:a28efbda4f83c6c3d59c8d',
    messagingSenderId: '623449718136',
    projectId: 'alerto-emergency-respons-1a1ba',
    authDomain: 'alerto-emergency-respons-1a1ba.firebaseapp.com',
    storageBucket: 'alerto-emergency-respons-1a1ba.firebasestorage.app',
    measurementId: 'G-S6Q4HE5ZPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3eHL5hIZRhgwHPEE1fTyHKjjuyfEApZo',
    appId: '1:623449718136:android:f132e5e1616bd5f8d59c8d',
    messagingSenderId: '623449718136',
    projectId: 'alerto-emergency-respons-1a1ba',
    storageBucket: 'alerto-emergency-respons-1a1ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn5uxnYeIzw29JNT3xsbGMT6v16-2sJO0',
    appId: '1:623449718136:ios:a62c1681eecca0aed59c8d',
    messagingSenderId: '623449718136',
    projectId: 'alerto-emergency-respons-1a1ba',
    storageBucket: 'alerto-emergency-respons-1a1ba.firebasestorage.app',
    iosBundleId: 'com.example.alertoEmergencyResponseApp',
  );
}
